/* Drop Tables */
DROP TABLE IF EXISTS PROCESS;
DROP TABLE IF EXISTS XMLTRANSFORMATION;

/* Drop Sequences */
DROP SEQUENCE IF EXISTS PROCESS_ID_SEQ;
DROP SEQUENCE IF EXISTS XMLTRANSFORMATION_ID_SEQ;

/* Create Sequences */
CREATE SEQUENCE PROCESS_ID_SEQ;
CREATE SEQUENCE XMLTRANSFORMATION_ID_SEQ;

/* Create Tables */
CREATE TABLE PROCESS (
	ID BIGINT NOT NULL,
	FINISHED TIMESTAMP WITHOUT TIME ZONE,
	OWNER CHARACTER VARYING(255) NOT NULL,
	PARAMS BYTEA,
	SCHEDULED TIMESTAMP WITHOUT TIME ZONE,
	STARTED TIMESTAMP WITHOUT TIME ZONE,
	PSTATE CHARACTER VARYING(255) NOT NULL,
	PTYPE CHARACTER VARYING(255) NOT NULL,
	PRIMARY KEY (ID)
) WITHOUT OIDS;

CREATE TABLE XMLTRANSFORMATION (
	ID BIGINT NOT NULL,
	CREATED TIMESTAMP WITHOUT TIME ZONE NOT NULL,
	DESCRIPTION CHARACTER VARYING(255),
	NAME CHARACTER VARYING(255) NOT NULL,
	OWNER CHARACTER VARYING(255) NOT NULL,
	TYPE CHARACTER VARYING(255) NOT NULL,
	XSLT TEXT NOT NULL,
	PRIMARY KEY (ID)
) WITHOUT OIDS;
