CREATE SEQUENCE SEQ_CONTENT;

CREATE TABLE CONTENT (
	ID NUMERIC NOT NULL,
	LANGUAGE VARCHAR NOT NULL,
        NAME VARCHAR NOT NULL,
        CONTENT VARCHAR NOT NULL,
        PRIMARY KEY (ID),
        CONSTRAINT languageName UNIQUE (LANGUAGE, NAME)
) WITHOUT OIDS;

/* Initialize content of panels "info" and "rules" for language version "cs", "en" */
INSERT INTO CONTENT(ID, LANGUAGE, NAME, CONTENT) VALUES (nextval('SEQ_CONTENT'), 'cs', 'info', '');
INSERT INTO CONTENT(ID, LANGUAGE, NAME, CONTENT) VALUES (nextval('SEQ_CONTENT'), 'en', 'info', '');
INSERT INTO CONTENT(ID, LANGUAGE, NAME, CONTENT) VALUES (nextval('SEQ_CONTENT'), 'cs', 'rules', '');
INSERT INTO CONTENT(ID, LANGUAGE, NAME, CONTENT) VALUES (nextval('SEQ_CONTENT'), 'en', 'rules', '');

/* order and visibility */
ALTER TABLE ARCHIVER ADD COLUMN ITEM_ORDER NUMERIC DEFAULT 0;
ALTER TABLE ARCHIVER ADD COLUMN HIDDEN BOOLEAN DEFAULT false;
