select r.UPDATE_TIMESTAMP as DD_updated,r.CISLO_RDCZ, r.URNNBN,
       r.PRIDELENO_DNE as URN_prideleno, r.FORMAT, r.DOSTUPNOST, r.SIGLA,
       r.CISLO_ZAKAZKY, r.FINANCOVANO, e.UPDATE_TIMESTAMP as IE_updated,
       e.CCNB, e.ISSN, e.DRUH_DOKUMENTU, e.NAZEV, e.AUTOR, e.ROK_VYDANI, 
       e.ROCNIK_PERIODIKA, e.MISTO_VYDANI
from 
    (select i.SIGLA,
    r1.UPDATE_TIMESTAMP,r1.CISLO_RDCZ, r1.URNNBN,
    r1.PRIDELENO_DNE, r1.FORMAT, r1.DOSTUPNOST, 
    r1.CISLO_ZAKAZKY, r1.FINANCOVANO, r1.INTELEKTUALNI_ENTITA
    from URNNBN.DIGITALNI_REPREZENTACE r1 left join URNNBN.INSTITUCE i
    on r1.INSTITUCE=i.INSTITUCE_ID) r left join URNNBN.INTELEKTUALNI_ENTITA e
                                      on r.INTELEKTUALNI_ENTITA=e.IE_ID 
                                      where e.DRUH_DOKUMENTU='GP'