CREATE TABLE URNNBNRESOLVATIONSTATISTIC
(
	REGISTRARCODE VARCHAR NOT NULL,
	YEAR NUMERIC NOT NULL,
	MONTH NUMERIC NOT NULL,
	RESOLVATIONS NUMERIC NOT NULL,
	PRIMARY KEY (REGISTRARCODE, YEAR, MONTH)
) WITHOUT OIDS;

CREATE INDEX URNNBN_REGISTERED ON URNNBN (REGISTERED);
CREATE INDEX URNNBNRESOLVATIONSTATISTIC_REGISTRARCODE ON URNNBNRESOLVATIONSTATISTIC (REGISTRARCODE);
