# PostgreSQL Configuration
db.url=jdbc:postgresql://localhost:5432/czidlo_core
db.useCursorFetch=true
db.user=czidlo
db.password=czidlo

# Apache Solr Configuration
#solr.url=http://localhost:8983/solr
solr.collection=my_collection
# Query to select data (default to all)
solr.query=*:*

# Elasticsearch Configuration
es.url=http://localhost:9200
es.index.name=czidlo_registrations_1
es.username=elastic
es.password=heslo

