#######################################
# Quartz Scheduler Configuration File #
#######################################
#
#
org.quartz.scheduler.instanceName=CzidloProcessScheduler
org.quartz.threadPool.threadCount=3
org.quartz.jobStore.class=org.quartz.simpl.RAMJobStore
org.quartz.threadPool.threadNamePrefix=PM-Quartz-