# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

#####################################
#-----------------------------------#
#- CONFIGURATION OF MODULE WEB-API -#
#-----------------------------------#
#####################################


#################################################
# global configuration used by multiple modules #
#################################################
#if this is set to true the application will not allow imports and other data updates

#@mandatory
czidlo.readOnly=false

#whether running in development mode. default value is false
#@mandatory
czidlo.develMode=false

#two-letter language code in URN:NBN schema according to ISO 3166, e. g. "cz"
#@mandatory
czidlo.languageCode=cz

#name of the administrator
#@optional
czidlo.admin.name=

#email of the administrator
#@optional
czidlo.admin.email=urnnbn@nkp.cz

#location of file for logs of all the apps; these logs are available to admin-users through web interface
#@mandatory 
czidlo.admin.logFile=/tmp/path/accessible/by/all/modules/admin.log
#URLs to response.xsd (used for building responses in xml)
#@mandatory
czidlo.api.v3.response-xsd=http://localhost:8080/api/v3/response.xsd
#@mandatory
czidlo.api.v4.response-xsd=http://localhost:8080/api/v4/response.xsd
#@mandatory
czidlo.api.v5.response-xsd=http://localhost:8080/api/v5/response.xsd
#@mandatory
czidlo.api.v6.response-xsd=http://localhost:8080/api/v6/response.xsd

#indexer - elasticsearch
indexer.es.baseUrl=https://elasticsearch.com
indexer.es.login=czidlo_user
indexer.es.password=password
indexer.es.index_search=czidlo_search_1
indexer.es.index_assign=czidlo_assign_1
indexer.es.index_resolve= czidlo_resolve_1

#indexer - czidlo database
indexer.db.url=jdbc:postgresql://localhost:5432/czidlo_core
indexer.db.login=czidlo
indexer.db.password=czidlo

###################################
# configuration of module web-api #
###################################

#base URL of web-api module
web-api.baseUrl=http://localhost:8080/web-api


####################################
# configuration of process-manager #
####################################

#directory for storing data (logs, output) of jobs
#@mandatory
process.scheduler.jobsDataDir=/tmp/path/to/process/dir

#primary database configuration used by processes
#@mandatory
czidlo.db.host=localhost
czidlo.db.port=5432
czidlo.db.database=czidlo_core
czidlo.db.login=czidlo
czidlo.db.password=czidlo

#maximal number of jobs (owned by admin users) running simultaneously
#@mandatory
process.scheduler.maxRunning.admin=2

#maximal number of jobs (owned by general users) running simultaneously
#@mandatory
process.scheduler.maxRunning.user=1


##########################
#  process OAI-ADAPTER   #
##########################

#@manadatory (use without the "http://" or "https://" prefix)
process.oaiAdapter.czidloApi.baseUrl=localhost:8080/api

#url of XSD to validate digital document registration data
#@manadatory
process.oaiAdapter.digDocRegistrationXsdUrl=http://localhost:8080/api/v5/digDocRegistration.xsd

#url of XSD to validate digital instance import data
#@manadatory
process.oaiAdapter.digInstImportXsdUrl=http://localhost:8080/api/v5/digInstImport.xsd

##########################
#   process ES-INDEXER   #
##########################

#@manadatory
process.indexer.es.baseUrl=http://localhost:9200
#@manadatory
process.indexer.es.login=czidlo_user
#@manadatory
process.indexer.es.password=password
#@manadatory
process.indexer.es.index_search=czidlo_search_1
#@manadatory
process.indexer.es.index_assign=czidlo_assign_1
#@manadatory
process.indexer.es.index_resolve=czidlo_resolve_1

#@manadatory
process.indexer.db.url=jdbc:postgresql://localhost:5432/czidlo_core
#@manadatory
process.indexer.db.login=czidlo
#@manadatory
process.indexer.db.password=czidlo
